name: Publish Docker image

on:
    workflow_dispatch:
        inputs:
            tags:
                description: Image tags
                required: false
                type: string
            build_args:
                description: Build-time variables
                required: false
                type: string
            platforms:
                description: Image platforms (you can specify multiple platforms separated by comma)
                required: false
                type: string
                default: linux/amd64
    workflow_call:
        inputs:
            tags:
                description: Image tags
                required: false
                type: string
            build_args:
                description: Build-time variables
                required: false
                type: string
            platforms:
                description: Image platforms (you can specify multiple platforms separated by comma)
                required: false
                type: string
                default: linux/amd64

jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v4
    
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
    
            # Will automatically make nice tags, see the table here https://github.com/docker/metadata-action#basic
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
                      ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
                  tags: |
                      type=semver,pattern={{version}}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v2
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
    
            -   name: Add SHORT_SHA env property with commit short sha
                run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

            - name: Build and push Docker images
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: ${{ github.event_name != 'pull_request' }}
                  platforms: linux/amd64, linux/arm64
                  tags: ${{ steps.meta.outputs.tags }}